language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: 'mover96-github'
    token:
      secure: 'ej4IZDetiSPYBAKFfGsgZcsaD1FZWE0mWIakXApWCc+C3TESjmDisvQbGukR6cDg+WCfQ1dNFhKoGkBMOHwbCCwWeWTbmK9OHlq81qzUFp1AWVlXSJQ0LKb3NF/cW4FLPChzOPb4z9FJnPB0onQKnKwmAnXjwMEFzdtcmajiOpPxCTa17LkS1KSv7Bizk06u1rZA7AyjygBNmfOhkwkPMso71/UlhWr9CQkRdHvtkK3E7RyWF+mG6JwlXsMaszmaSyThUgvKF/OEmvb5iKLnIQu5DgF3sWAV/SdKvcFKJH0Rm5Vc1hJb6oZH9Iz99yiEijXkoNKDmjXJgt2aJauxm2vQ/JAGs0pPDnesP4gWsK7J2bQ/sFKm+lwdG9SThYqzCZ1AZWPc7AraQRvfX9zYDb9apj5dlw6swQMbCRK1SI1WU3sJQfOJoOEK/UT45xuPfgl29dkmS0RuRnzpAUZ1b/Vd+q70tBifQW+z05kgDanznDjlmUDcWc/Aoebd9+LDy269HVifV6wtiKXkNlf5NagCOEa+oc58l9y7q6/hhhpb4mu4KeQP0x1Jj7W9Upo8/qIPpzzQ79wvBgpO0tD6Neord32Dk8gqiPTDIA0uBlm72pAzcvyAtO2/tR2CAxEtpDYaiHLVJNFttezn98DYQL66jqNVexwTtQXGp8xUSls='
jdk:
- oraclejdk8
script:
# - ant build
- sonar-scanner
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
# env:
#   global:
#     secure: HazKneJzhuC+FsJjPkPRhk3c+gDi7upgMOi07em2DQz/JyBPVn+jBh82XH+BZ0vEGonJY1VV1VOr15TDR80ZmNsQQYkc4oWnPLumMRw7S24m+mKsRKNjF5PcmUFIKbNhVnwyKetzGiyPQx+Yn6p1kiqFhC6DmADB05mIDqiFV8+qil0e43+awhMhoha2d8jYBCBAl1UvP/CW+1is9u3Y1GRDtSx+3YRvydyZikoJiOTJJndGl/z8PON0cgzJYaOC3pLOTHqHocrWYJ+QXuvCrjMi1N6sXyC3tQPHx/gLLDhbdsZvYZUUv7Vr31T4UgyK2uEeNOFKtNjLeoD7W3fYKhRGjX7xQEu+LtOXCH+hReHFyQUL4BRR9Ishz5NWhV5lp45q9i1q8dRIIZ0852NkztyaBRMIhs/js1heIezPP1g3LwMhPxbYabNuGWHcDCfqvTnmH9mMXmTH9AeF1MV4o9AaBihHRGySDMZfZlwXsVFkOQdaHAliUD4yDovqLbrvOUjyFbMqhjj9BZLP+AcQsY621x4IqxXgOVHmT3fA3FywKM/998h4UUlVGm8nWMyny69REPQDpTAxaU0uoGZ5tSJopk8xRjt2zZrwetb6id1UFbmeRV5aIPwxNzXuqX/R0G2BV8h6kZFB1Sp1i0NxiIE3Sn0jPNXQgVxWgFqSyyc=
